<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('products')->delete();
        
        DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 2,
                'title' => 'Totoro figure',
                'description' => 'A heat-resistant spatula featuring everyone\'s favorite fire demon.',
                'price' => '22.70',
                'stock' => 50,
                'discount' => '0.00',
                'movie_id' => 2,
                'created_at' => '2026-04-17 05:12:50',
                'updated_at' => '2026-04-17 14:43:47',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 5,
                'title' => 'Totoro stuff',
                'description' => 'Nice Stuff',
                'price' => '17.00',
                'stock' => 80,
                'discount' => '10.00',
                'movie_id' => 6,
                'created_at' => '2026-04-17 11:57:12',
                'updated_at' => '2026-04-19 12:28:50',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 6,
                'title' => 'Ghibli pillow',
                'description' => 'Very soft pillow.',
                'price' => '29.00',
                'stock' => 300,
                'discount' => '2.00',
                'movie_id' => 2,
                'created_at' => '2026-04-17 14:03:29',
                'updated_at' => '2026-04-17 14:03:29',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 7,
                'title' => 'Kiki Calendar',
                'description' => 'Very nice calendar.',
                'price' => '20.00',
                'stock' => 410,
                'discount' => '3.00',
                'movie_id' => 4,
                'created_at' => '2026-04-17 14:12:13',
                'updated_at' => '2026-04-24 03:14:19',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 9,
                'title' => 'Totoro Bag',
                'description' => 'Cute and nice nag',
                'price' => '49.00',
                'stock' => 11,
                'discount' => '20.00',
                'movie_id' => 1,
                'created_at' => '2026-04-17 22:42:04',
                'updated_at' => '2026-04-23 12:54:31',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 10,
                'title' => 'Cute bag and figure',
                'description' => 'Nice charaters',
                'price' => '28.00',
                'stock' => 39,
                'discount' => '10.00',
                'movie_id' => 3,
                'created_at' => '2026-04-17 22:43:24',
                'updated_at' => '2026-04-23 12:54:31',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 11,
                'title' => 'Calcifier',
                'description' => 'Cute fire',
                'price' => '20.00',
                'stock' => 299,
                'discount' => '10.00',
                'movie_id' => 3,
                'created_at' => '2026-04-17 22:44:03',
                'updated_at' => '2026-05-02 11:57:15',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 12,
                'title' => 'Ponyo earphone',
                'description' => 'Convenient and cute stuff',
                'price' => '124.87',
                'stock' => 38,
                'discount' => '10.00',
                'movie_id' => 5,
                'created_at' => '2026-04-17 22:55:56',
                'updated_at' => '2026-04-24 03:14:19',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 13,
                'title' => 'Nice Keychain',
                'description' => 'Molestias quod ipsum aut est quo consectetur. Iusto sed voluptatem nihil ut. Eaque et deserunt ab. Reprehenderit voluptate qui saepe dolorem optio officia ex officia.',
                'price' => '12.00',
                'stock' => 24,
                'discount' => '10.00',
                'movie_id' => 2,
                'created_at' => '2026-04-17 22:55:56',
                'updated_at' => '2026-04-23 12:44:28',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 14,
                'title' => 'Cute Calcifier',
                'description' => 'Soft and nice for decoration',
                'price' => '15.00',
                'stock' => 30,
                'discount' => '10.00',
                'movie_id' => 2,
                'created_at' => '2026-04-17 22:55:56',
                'updated_at' => '2026-04-23 05:51:01',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 15,
                'title' => 'Assumenda maiores velit explicabo.',
                'description' => 'Excepturi voluptas quo voluptas consequuntur. Nam explicabo voluptas ipsam laudantium in. Et nostrum eum libero. Aperiam aspernatur officiis quibusdam esse enim in voluptas.',
                'price' => '19.00',
                'stock' => 200,
                'discount' => '2.00',
                'movie_id' => 6,
                'created_at' => '2026-04-17 22:55:56',
                'updated_at' => '2026-04-18 10:34:55',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 17,
                'title' => 'Vitae similique ea quasi.',
                'description' => 'Aut eveniet totam alias exercitationem sapiente necessitatibus ipsa. Cupiditate aut et velit quos voluptas. Quasi aut occaecati quae qui hic quaerat id. Nemo molestiae voluptas sed delectus.',
                'price' => '175.35',
                'stock' => 0,
                'discount' => '0.00',
                'movie_id' => 3,
                'created_at' => '2026-04-17 22:55:56',
                'updated_at' => '2026-05-02 11:57:39',
                'deleted_at' => '2026-05-02 11:57:39',
            ),
            12 => 
            array (
                'id' => 18,
                'title' => 'Cute Figure',
                'description' => 'A rerum tempore sit. Voluptates quisquam vitae inventore commodi tempora et nihil voluptatem.',
                'price' => '42.16',
                'stock' => 21,
                'discount' => '0.00',
                'movie_id' => 2,
                'created_at' => '2026-04-17 22:55:56',
                'updated_at' => '2026-04-24 03:42:20',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 19,
                'title' => 'Light fire',
                'description' => 'Distinctio necessitatibus nesciunt excepturi molestias corporis architecto est. Tempora voluptas unde consectetur nesciunt. Vitae nihil cumque perspiciatis.',
                'price' => '28.00',
                'stock' => 24,
                'discount' => '5.00',
                'movie_id' => 2,
                'created_at' => '2026-04-17 22:55:56',
                'updated_at' => '2026-04-30 15:19:20',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 20,
                'title' => 'CatBus',
                'description' => 'Eius quis voluptate ut. Quidem veritatis iure iste non veritatis sint consequatur. Dolorum rerum commodi in eum possimus temporibus eos.',
                'price' => '35.39',
                'stock' => 8,
                'discount' => '5.00',
                'movie_id' => 2,
                'created_at' => '2026-04-17 22:55:56',
                'updated_at' => '2026-04-24 03:52:29',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 21,
                'title' => 'Dust bunny bag',
                'description' => 'Amet distinctio recusandae quia dolor pariatur repudiandae voluptates. Beatae rerum corporis sint debitis. Sequi libero accusantium eum fuga molestias.',
                'price' => '166.07',
                'stock' => 27,
                'discount' => '5.00',
                'movie_id' => 2,
                'created_at' => '2026-04-17 22:55:56',
                'updated_at' => '2026-04-24 03:52:56',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 22,
                'title' => 'Cute pencil case',
                'description' => 'Very nice stuff for kid',
                'price' => '6.00',
                'stock' => 19,
                'discount' => '15.00',
                'movie_id' => 3,
                'created_at' => '2026-04-17 22:57:39',
                'updated_at' => '2026-04-24 03:50:53',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 23,
                'title' => 'Small characters',
                'description' => 'Voluptas repudiandae incidunt repellat quisquam. Consectetur delectus rerum esse in quam. Debitis quis rerum dicta temporibus.',
                'price' => '131.54',
                'stock' => 42,
                'discount' => '15.00',
                'movie_id' => 3,
                'created_at' => '2026-04-17 22:57:39',
                'updated_at' => '2026-04-24 03:51:52',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 24,
                'title' => 'Playing Calcifier',
                'description' => 'Nihil eveniet labore nobis quibusdam. Quam veritatis minima quos dolor eius sapiente. Quod quam facere explicabo et. Iure qui nobis cumque tempora voluptatem fugiat. Rerum nisi voluptas molestias rerum enim beatae blanditiis.',
                'price' => '43.33',
                'stock' => 43,
                'discount' => '10.00',
                'movie_id' => 3,
                'created_at' => '2026-04-17 22:57:39',
                'updated_at' => '2026-05-04 15:23:06',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 25,
                'title' => 'Kid bag',
                'description' => 'Voluptatem autem voluptatem sed est. Deserunt nostrum autem est aliquam quae iste. Sint doloribus dolor dolor et similique asperiores officia quia.',
                'price' => '23.85',
                'stock' => 19,
                'discount' => '15.00',
                'movie_id' => 3,
                'created_at' => '2026-04-17 22:57:39',
                'updated_at' => '2026-05-02 11:56:25',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 26,
                'title' => 'Anime pillow',
                'description' => 'Natus reiciendis quis illum et non pariatur libero. Ullam consectetur ad rem quod. Voluptate molestiae laborum est sint beatae unde saepe inventore.',
                'price' => '111.99',
                'stock' => 2,
                'discount' => '15.00',
                'movie_id' => 3,
                'created_at' => '2026-04-17 22:57:39',
                'updated_at' => '2026-04-24 03:50:33',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 27,
                'title' => 'Totoro wallet',
                'description' => 'Dolore voluptatem voluptatem a dolorem culpa. Eum optio pariatur odit omnis voluptas sed. Perferendis vitae pariatur excepturi inventore quam sint veritatis. Reprehenderit voluptas culpa repellendus dolor incidunt veniam.',
                'price' => '15.00',
                'stock' => 450,
                'discount' => '10.00',
                'movie_id' => 3,
                'created_at' => '2026-04-17 22:57:39',
                'updated_at' => '2026-05-01 02:54:32',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 28,
                'title' => 'Noface Light',
                'description' => 'Ipsa ratione quia vitae vitae. Voluptatum recusandae et dolores omnis quibusdam consequatur dicta. Totam optio voluptatem aut vero. Recusandae fuga magnam nesciunt ut.',
                'price' => '103.33',
                'stock' => 16,
                'discount' => '10.00',
                'movie_id' => 3,
                'created_at' => '2026-04-17 22:57:39',
                'updated_at' => '2026-04-24 03:53:28',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 29,
                'title' => 'Small figure',
                'description' => 'Aut ducimus eius vel maiores dolorum voluptatem ut. Error voluptatem et laboriosam voluptatibus.',
                'price' => '167.63',
                'stock' => 37,
                'discount' => '5.00',
                'movie_id' => 3,
                'created_at' => '2026-04-17 22:57:39',
                'updated_at' => '2026-04-24 03:48:15',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 30,
                'title' => 'Anime collection',
                'description' => 'Qui voluptas amet totam error quo. Quia alias consequatur iure dolorem nam id. Deleniti id assumenda non blanditiis earum accusantium.',
                'price' => '127.68',
                'stock' => 20,
                'discount' => '0.00',
                'movie_id' => 3,
                'created_at' => '2026-04-17 22:57:39',
                'updated_at' => '2026-05-02 11:57:15',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 31,
                'title' => 'Nice Calendar',
                'description' => 'Beatae quia alias sunt et. Quis libero aperiam minima. Occaecati sint aut quasi deleniti qui commodi optio.',
                'price' => '96.62',
                'stock' => 36,
                'discount' => '15.00',
                'movie_id' => 3,
                'created_at' => '2026-04-17 22:57:39',
                'updated_at' => '2026-04-24 03:49:27',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 32,
                'title' => 'Cute character keychain',
                'description' => 'Super cute and small keychain for everyone',
                'price' => '27.00',
                'stock' => 5,
                'discount' => '15.00',
                'movie_id' => 3,
                'created_at' => '2026-04-17 22:58:41',
                'updated_at' => '2026-04-24 03:43:31',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 33,
                'title' => 'Black Cat',
                'description' => 'Omnis sapiente magni itaque eos. Veniam quia id dolor explicabo. Illo ut quisquam quia enim eveniet.',
                'price' => '23.00',
                'stock' => 21,
                'discount' => '5.00',
                'movie_id' => 4,
                'created_at' => '2026-04-17 22:58:41',
                'updated_at' => '2026-05-05 04:19:26',
                'deleted_at' => '2026-05-05 04:19:26',
            ),
            28 => 
            array (
                'id' => 34,
                'title' => 'JiJi cat',
                'description' => 'Soft black cat',
                'price' => '138.51',
                'stock' => 8,
                'discount' => '5.00',
                'movie_id' => 4,
                'created_at' => '2026-04-17 22:58:41',
                'updated_at' => '2026-04-18 14:28:44',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 35,
                'title' => 'JiJi and friend',
                'description' => 'Ipsam odio adipisci quia. Aperiam quis sunt placeat. Distinctio perferendis quisquam recusandae consequatur aut.',
                'price' => '79.40',
                'stock' => 23,
                'discount' => '0.00',
                'movie_id' => 4,
                'created_at' => '2026-04-17 22:58:41',
                'updated_at' => '2026-04-24 03:46:23',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 36,
                'title' => 'Kiki',
                'description' => 'Labore est architecto non quibusdam. Eligendi enim et mollitia velit. Inventore et vitae nulla maiores. Quos vero delectus excepturi quos repellendus blanditiis iusto. Nulla accusamus rerum voluptas nesciunt dolor.',
                'price' => '140.49',
                'stock' => 41,
                'discount' => '5.00',
                'movie_id' => 4,
                'created_at' => '2026-04-17 22:58:41',
                'updated_at' => '2026-04-24 03:46:54',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 37,
                'title' => 'No face',
                'description' => 'Libero nam eveniet non in. Quas modi est sit quod. Et inventore ipsa ut et iste. Nostrum ratione architecto perspiciatis impedit reprehenderit cumque et.',
                'price' => '123.48',
                'stock' => 26,
                'discount' => '0.00',
                'movie_id' => 4,
                'created_at' => '2026-04-17 22:58:41',
                'updated_at' => '2026-04-24 03:39:39',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 38,
                'title' => 'Et qui nihil enim.',
                'description' => 'Placeat blanditiis qui ex consequatur et. Dolorem quos voluptas iure laudantium inventore voluptatem laudantium. At rerum repellat aperiam tempora. Sunt et est quia dicta et dolor. Excepturi amet nihil dolore delectus at.',
                'price' => '192.85',
                'stock' => 17,
                'discount' => '15.00',
                'movie_id' => 4,
                'created_at' => '2026-04-17 22:58:41',
                'updated_at' => '2026-05-02 11:54:52',
                'deleted_at' => '2026-05-02 11:54:52',
            ),
            33 => 
            array (
                'id' => 39,
                'title' => 'Pillow with ears',
                'description' => 'Quidem incidunt voluptates omnis sapiente cupiditate ex odio. Consequatur debitis blanditiis et ea sit repudiandae. Ducimus nihil quidem aut quod soluta odio ullam. Distinctio explicabo impedit autem omnis perspiciatis qui.',
                'price' => '194.57',
                'stock' => 45,
                'discount' => '0.00',
                'movie_id' => 4,
                'created_at' => '2026-04-17 22:58:41',
                'updated_at' => '2026-04-24 03:54:18',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 40,
                'title' => 'Cat JiJi and catbus',
                'description' => 'Eos unde aut voluptates. At voluptatibus dolor explicabo autem tempore. Beatae et recusandae esse. Totam rerum sint eligendi. Doloremque architecto eum voluptas esse sint possimus.',
                'price' => '120.08',
                'stock' => 22,
                'discount' => '15.00',
                'movie_id' => 4,
                'created_at' => '2026-04-17 22:58:41',
                'updated_at' => '2026-04-24 03:41:13',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 41,
                'title' => 'Blind box',
                'description' => 'Aut voluptatem voluptatibus velit non. Libero rerum assumenda illo error tenetur quis voluptatibus nostrum. Unde ipsum eos ipsam quos explicabo. Quam tenetur et voluptates qui.',
                'price' => '105.23',
                'stock' => 3,
                'discount' => '5.00',
                'movie_id' => 4,
                'created_at' => '2026-04-17 22:58:41',
                'updated_at' => '2026-04-24 03:40:06',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 42,
                'title' => 'Soft Pillow',
                'description' => 'Sunt aut amet et qui id harum quia id. Et iste quod molestiae necessitatibus quis quae. Et ut doloremque excepturi delectus non. Nemo sit reiciendis et molestiae id consequatur cumque.',
                'price' => '134.29',
                'stock' => 36,
                'discount' => '15.00',
                'movie_id' => 5,
                'created_at' => '2026-04-17 22:59:06',
                'updated_at' => '2026-05-10 11:44:37',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 43,
                'title' => 'Moving castle',
                'description' => 'Voluptatem expedita perferendis aut dolor consequatur et ut autem. Voluptates ratione facilis voluptatibus est earum a. Aut provident autem deleniti eveniet officia tempora vel. Voluptas molestiae accusamus aut doloribus.',
                'price' => '29.41',
                'stock' => 13,
                'discount' => '10.00',
                'movie_id' => 5,
                'created_at' => '2026-04-17 22:59:06',
                'updated_at' => '2026-04-24 03:28:02',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 44,
                'title' => 'Dust bunny',
                'description' => 'Ipsa qui voluptatibus fugiat consectetur consectetur quia distinctio voluptas. Et sint eaque harum est vero.',
                'price' => '61.97',
                'stock' => 300,
                'discount' => '5.00',
                'movie_id' => 5,
                'created_at' => '2026-04-17 22:59:06',
                'updated_at' => '2026-04-24 12:17:30',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 45,
                'title' => 'Nice bag',
                'description' => 'Quisquam omnis vitae consequatur qui. Cum unde tempora aliquid molestias sed. Nostrum voluptates molestias et aliquam est.',
                'price' => '103.87',
                'stock' => 392,
                'discount' => '15.00',
                'movie_id' => 5,
                'created_at' => '2026-04-17 22:59:06',
                'updated_at' => '2026-05-05 05:30:14',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 46,
                'title' => 'Cum perferendis ipsam.',
                'description' => 'Deserunt magni minima fugit fuga voluptatem sit similique. Consequatur sequi possimus ut qui accusamus ipsam animi voluptatum.',
                'price' => '52.38',
                'stock' => 100,
                'discount' => '15.00',
                'movie_id' => 5,
                'created_at' => '2026-04-17 22:59:06',
                'updated_at' => '2026-04-24 12:17:08',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 47,
                'title' => 'Soft fire',
                'description' => 'Harum et illo soluta. Cumque velit fugiat ex ipsam dolor qui aliquid doloribus. Quia voluptatibus sed voluptatem sint. Quas magnam consequuntur explicabo omnis ex optio.',
                'price' => '46.33',
                'stock' => 40,
                'discount' => '15.00',
                'movie_id' => 5,
                'created_at' => '2026-04-17 22:59:06',
                'updated_at' => '2026-04-24 12:17:39',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 48,
                'title' => 'Dignissimos quidem harum aut.',
                'description' => 'In aut dignissimos est optio nisi voluptatum eaque. Quo asperiores labore et natus pariatur ducimus. Quam maiores reprehenderit dolor minima asperiores velit suscipit. Aperiam beatae vitae distinctio voluptatem maiores voluptatibus. Quisquam repellendus tenetur omnis qui deleniti dolores.',
                'price' => '102.80',
                'stock' => 400,
                'discount' => '0.00',
                'movie_id' => 5,
                'created_at' => '2026-04-17 22:59:06',
                'updated_at' => '2026-05-02 13:29:29',
                'deleted_at' => '2026-05-02 13:29:29',
            ),
            43 => 
            array (
                'id' => 49,
                'title' => 'Calcifier',
                'description' => 'Nobis et quidem culpa autem in nostrum. Natus porro aliquid iste est voluptatum et quis. Dolor odit cum nemo et atque. Et eaque nulla dolorem id officiis.',
                'price' => '24.87',
                'stock' => 70,
                'discount' => '15.00',
                'movie_id' => 5,
                'created_at' => '2026-04-17 22:59:06',
                'updated_at' => '2026-04-24 12:18:10',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 50,
                'title' => 'Black stuff',
                'description' => 'Ipsum error et asperiores sit perspiciatis iure voluptatem mollitia. Ut in sit omnis velit omnis nisi. Qui non error necessitatibus aliquam recusandae aspernatur. Facilis molestiae rem error sed.',
                'price' => '18.54',
                'stock' => 500,
                'discount' => '0.00',
                'movie_id' => 5,
                'created_at' => '2026-04-17 22:59:06',
                'updated_at' => '2026-04-24 12:17:48',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 51,
                'title' => 'Ponyo',
                'description' => 'Corrupti nemo voluptatem vel excepturi. Laborum ut ratione reprehenderit dolore quo cumque. Rerum assumenda porro odit numquam.',
                'price' => '86.18',
                'stock' => 45,
                'discount' => '10.00',
                'movie_id' => 5,
                'created_at' => '2026-04-17 22:59:06',
                'updated_at' => '2026-04-24 03:55:45',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 52,
                'title' => 'Mei',
                'description' => 'Voluptates dolore voluptas temporibus vitae repellendus quia. Ipsam omnis aut delectus fugit. Quaerat aut ratione ducimus magnam et. Sunt modi neque possimus architecto.',
                'price' => '33.00',
                'stock' => 42,
                'discount' => '5.00',
                'movie_id' => 6,
                'created_at' => '2026-04-17 22:59:48',
                'updated_at' => '2026-05-04 15:23:06',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 53,
                'title' => 'Ad ad neque qui.',
                'description' => 'Ratione nihil qui possimus et cum. Dolore laboriosam aliquam corrupti saepe. Et ea minus vel dignissimos earum voluptas.',
                'price' => '166.80',
                'stock' => 79,
                'discount' => '0.00',
                'movie_id' => 6,
                'created_at' => '2026-04-17 22:59:48',
                'updated_at' => '2026-04-30 06:55:45',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 54,
                'title' => 'Soft Pillow',
                'description' => 'Eum ea ex sapiente eos consequatur fugiat eum fugiat. Ex dolor enim est labore odio dolor. Ratione est quis qui non ex rerum laborum.',
                'price' => '183.17',
                'stock' => 0,
                'discount' => '10.00',
                'movie_id' => 1,
                'created_at' => '2026-04-17 22:59:48',
                'updated_at' => '2026-05-08 15:20:16',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 55,
                'title' => 'Mini pillow',
                'description' => 'Nemo saepe tempora maxime id enim. Totam molestiae temporibus est accusamus asperiores qui. Non deleniti commodi occaecati et nihil dolores unde veniam.',
                'price' => '168.05',
                'stock' => 100,
                'discount' => '15.00',
                'movie_id' => 6,
                'created_at' => '2026-04-17 22:59:48',
                'updated_at' => '2026-05-04 13:08:52',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 56,
                'title' => 'Cartoon Puzzle',
                'description' => 'Spend your time on assembling this cute stuff',
                'price' => '40.00',
                'stock' => 25,
                'discount' => '5.00',
                'movie_id' => 2,
                'created_at' => '2026-04-17 22:59:48',
                'updated_at' => '2026-04-30 15:14:24',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 57,
                'title' => 'KiKi',
                'description' => 'Cum qui quod sapiente doloribus. Non et culpa ut unde quos. Natus veritatis suscipit officiis dignissimos earum. Illum adipisci nihil dicta.',
                'price' => '18.11',
                'stock' => 298,
                'discount' => '15.00',
                'movie_id' => 6,
                'created_at' => '2026-04-17 22:59:48',
                'updated_at' => '2026-04-30 06:55:45',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 58,
                'title' => 'Character clock',
                'description' => 'Qui dicta libero voluptas et ipsam qui. Et ut velit sint nemo rerum aperiam cupiditate. Nam velit veniam amet saepe. Animi id quos deserunt sit incidunt.',
                'price' => '55.34',
                'stock' => 501,
                'discount' => '5.00',
                'movie_id' => 6,
                'created_at' => '2026-04-17 22:59:48',
                'updated_at' => '2026-04-24 12:16:51',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 59,
                'title' => 'Soft Totoro shoes',
                'description' => 'Voluptatibus qui tempora pariatur perspiciatis ut rerum. Rerum velit dolore molestias. Sapiente et necessitatibus deleniti quis laudantium suscipit. Pariatur quis cupiditate autem vero minima eos necessitatibus.',
                'price' => '115.21',
                'stock' => 16,
                'discount' => '10.00',
                'movie_id' => 1,
                'created_at' => '2026-04-17 22:59:48',
                'updated_at' => '2026-05-05 05:30:14',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 62,
                'title' => 'Cat bus',
                'description' => 'Very cute syuff',
                'price' => '17.00',
                'stock' => 178,
                'discount' => '0.00',
                'movie_id' => 3,
                'created_at' => '2026-04-18 10:06:38',
                'updated_at' => '2026-05-04 13:00:07',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 63,
                'title' => 'Cute light',
                'description' => 'Nice and special',
                'price' => '71.00',
                'stock' => 85,
                'discount' => '0.00',
                'movie_id' => 3,
                'created_at' => '2026-04-18 10:10:14',
                'updated_at' => '2026-05-08 14:19:27',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 64,
                'title' => 'Special bag',
                'description' => 'big bag',
                'price' => '190.00',
                'stock' => 86,
                'discount' => '0.00',
                'movie_id' => 5,
                'created_at' => '2026-04-18 10:11:10',
                'updated_at' => '2026-05-10 11:44:37',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 65,
                'title' => 'Cute bunny',
                'description' => 'soft and furry',
                'price' => '8.00',
                'stock' => 89,
                'discount' => '0.00',
                'movie_id' => 1,
                'created_at' => '2026-04-18 10:11:52',
                'updated_at' => '2026-05-04 13:09:25',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 66,
                'title' => 'Cute pillow and no face',
                'description' => 'Good for decoration',
                'price' => '24.00',
                'stock' => 80,
                'discount' => '11.00',
                'movie_id' => 6,
                'created_at' => '2026-04-18 12:49:22',
                'updated_at' => '2026-04-30 15:26:29',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 67,
                'title' => 'Totoro Characters',
                'description' => 'Cute design',
                'price' => '40.00',
                'stock' => 298,
                'discount' => '0.00',
                'movie_id' => 1,
                'created_at' => '2026-04-18 14:00:52',
                'updated_at' => '2026-05-08 14:19:27',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 68,
                'title' => 'Kiki picture',
                'description' => 'Signature picture',
                'price' => '18.00',
                'stock' => 40,
                'discount' => '0.00',
                'movie_id' => 4,
                'created_at' => '2026-04-18 14:02:43',
                'updated_at' => '2026-04-24 12:16:13',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 69,
                'title' => 'Castle pillow',
                'description' => 'Very beautiful',
                'price' => '27.00',
                'stock' => 298,
                'discount' => '6.00',
                'movie_id' => 6,
                'created_at' => '2026-04-18 14:04:18',
                'updated_at' => '2026-05-10 11:44:37',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 70,
                'title' => 'No face',
                'description' => 'No face pillow',
                'price' => '19.00',
                'stock' => 229,
                'discount' => '0.00',
                'movie_id' => 2,
                'created_at' => '2026-04-20 05:07:58',
                'updated_at' => '2026-05-05 05:30:14',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 71,
                'title' => 'Totoro hair band',
                'description' => 'Very soft and cute design',
                'price' => '34.00',
                'stock' => 599,
                'discount' => '13.00',
                'movie_id' => 1,
                'created_at' => '2026-04-23 13:29:22',
                'updated_at' => '2026-05-04 13:00:07',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 72,
                'title' => 'Cute characters',
                'description' => 'Good for play or decoration',
                'price' => '34.00',
                'stock' => 300,
                'discount' => '0.00',
                'movie_id' => 5,
                'created_at' => '2026-05-02 11:56:02',
                'updated_at' => '2026-05-02 12:39:51',
                'deleted_at' => '2026-05-02 12:39:51',
            ),
            65 => 
            array (
                'id' => 73,
                'title' => 'Cat calendar',
                'description' => 'For JiJi fan',
                'price' => '45.00',
                'stock' => 300,
                'discount' => '0.00',
                'movie_id' => 1,
                'created_at' => '2026-05-02 13:04:46',
                'updated_at' => '2026-05-02 13:05:29',
                'deleted_at' => '2026-05-02 13:05:29',
            ),
            66 => 
            array (
                'id' => 74,
                'title' => 'Ceramic bow',
                'description' => 'For Calcifier fan',
                'price' => '55.00',
                'stock' => 298,
                'discount' => '0.00',
                'movie_id' => 3,
                'created_at' => '2026-05-02 13:06:47',
                'updated_at' => '2026-05-02 13:08:50',
                'deleted_at' => '2026-05-02 13:08:50',
            ),
            67 => 
            array (
                'id' => 75,
                'title' => 'Cute characters',
                'description' => 'Nice stuff for fan',
                'price' => '30.00',
                'stock' => 894,
                'discount' => '20.00',
                'movie_id' => 5,
                'created_at' => '2026-05-02 13:31:48',
                'updated_at' => '2026-05-10 11:44:37',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 76,
                'title' => 'Nice calendar',
                'description' => 'for KiKi fan',
                'price' => '71.00',
                'stock' => 17,
                'discount' => '0.00',
                'movie_id' => 1,
                'created_at' => '2026-05-02 13:50:37',
                'updated_at' => '2026-05-08 14:19:27',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 77,
                'title' => 'Cuttie decoration',
                'description' => 'Very good quality',
                'price' => '38.00',
                'stock' => 88,
                'discount' => '18.00',
                'movie_id' => 6,
                'created_at' => '2026-05-04 13:07:42',
                'updated_at' => '2026-05-10 11:44:37',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 78,
                'title' => 'Soft cat bus',
                'description' => 'Super cute item',
                'price' => '33.00',
                'stock' => 0,
                'discount' => '20.00',
                'movie_id' => 1,
                'created_at' => '2026-05-05 04:20:42',
                'updated_at' => '2026-05-08 15:18:54',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 79,
                'title' => 'Mei and totoro',
                'description' => 'Very cute and nice color',
                'price' => '70.00',
                'stock' => 700,
                'discount' => '7.00',
                'movie_id' => 1,
                'created_at' => '2026-05-10 11:48:45',
                'updated_at' => '2026-05-10 11:48:45',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}