import { type MovieCategory, type CartItem, type Order } from "./dataType";

export const moviesList: MovieCategory[] = [
   {
      id: 1,
      title: "My Neighbor Totoro",
      img: "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781421561226/my-neighbor-totoro-picture-book-new-edition-9781421561226_hr.jpg",
   },
   {
      id: 2,
      title: "Spirited Away",
      img: "https://example.com/spirited_away.jpg",
   },
   {
      id: 3,
      title: "Princess Mononoke",
      img: "https://example.com/princess_mononoke.jpg",
   },
   {
      id: 4,
      title: "Howl's Moving Castle",
      img: "https://example.com/howls_moving_castle.jpg",
   },
   {
      id: 5,
      title: "Kiki's Delivery Service",
      img: "https://s3.amazonaws.com/nightjarprod/content/uploads/sites/344/2026/03/13163130/Aufa4YdZIv4AXpR9rznwVA5SEfd-1-scaled.jpg",
   },
   { id: 6, title: "Ponyo", img: "https://example.com/ponyo.jpg" },
   {
      id: 7,
      title: "The Wind Rises",
      img: "https://example.com/the_wind_rises.jpg",
   },
   {
      id: 8,
      title: "Castle in the Sky",
      img: "https://example.com/castle_in_the_sky.jpg",
   },
   {
      id: 9,
      title: "Ponyo",
      img: "https://images.fathomevents.com/image/upload/w_400,dpr_2,f_auto,q_auto/v1743550042/Events/2025/2013/1000x1480_Ponyo_FE_Ticketing.jpg.jpg",
   },
   {
      id: 10,
      title: "Nausicaä of the Valley of the Wind",
      img: "https://example.com/nausicaa.jpg",
   },
];

export const mockCartItems: CartItem[] = [
   {
      id: 1,
      cartId: 1,
      quantity: 2,
      productId: 1,
      title: "Totoro Plush Toy",
      price: 29.99,
      discount: 10,
      imageUrl:
         "https://enez76gwp29.exactdn.com/wp-content/uploads/2020/04/productimage208903327_2nd.jpg?strip=all&lossy=1&ssl=1",
   },
   {
      id: 2,
      cartId: 1,
      quantity: 1,
      productId: 2,
      title: "Spirited Away Art Book",
      price: 19.99,
      discount: 0,
      imageUrl:
         "https://enez76gwp29.exactdn.com/wp-content/uploads/2020/04/productimage120813380_2nd.jpg?strip=all&lossy=1&ssl=1",
   },
   {
      id: 3,
      cartId: 1,
      quantity: 3,
      productId: 3,
      title: "My Neighbor Totoro T-Shirt",
      price: 24.99,
      discount: 15,
      imageUrl: "https://i.ebayimg.com/images/g/GNcAAOSw7MNiYT6T/s-l1200.jpg",
   },
   {
      id: 4,
      cartId: 2,
      quantity: 1,
      productId: 4,
      title: "Princess Mononoke Poster",
      price: 14.99,
      discount: 0,
      imageUrl: "https://example.com/princess_mononoke.jpg",
   },
   {
      id: 5,
      cartId: 2,
      quantity: 1,
      productId: 5,
      title: "Howl's Moving Castle Figurine",
      price: 39.99,
      discount: 20,
      imageUrl: "https://example.com/howls_moving_castle.jpg",
   },
];

export const mockOrdersList: Order[] = [
   {
      id: 1,
      userId: 1,
      totalAmount: 59.98,
      status: "delivered",
      createdAt: "2024-01-15T10:30:00Z",
      paymentMethod: "Credit Card",
      deliveryFee: 5.99,
      paymentStatus: "paid",
   },
   {
      id: 2,
      userId: 2,
      totalAmount: 24.99,
      status: "shipped",
      createdAt: "2024-02-20T14:45:00Z",
      paymentMethod: "Credit Card",
      deliveryFee: 5.99,
      paymentStatus: "paid",
   },
   {
      id: 3,
      userId: 3,
      totalAmount: 79.97,
      status: "processing",
      createdAt: "2024-03-10T09:15:00Z",
      paymentMethod: "Credit Card",
      deliveryFee: 5.99,
      paymentStatus: "paid",
   },
   {
      id: 4,
      userId: 1,
      totalAmount: 14.99,
      status: "pending",
      createdAt: "2024-04-05T16:20:00Z",
      paymentMethod: "Credit Card",
      deliveryFee: 5.99,
      paymentStatus: "paid",
   },
   {
      id: 5,
      userId: 4,
      totalAmount: 49.98,
      status: "delivered",
      createdAt: "2024-05-12T11:00:00Z",
      paymentMethod: "Credit Card",
      deliveryFee: 5.99,
      paymentStatus: "paid",
   },
   {
      id: 6,
      userId: 2,
      totalAmount: 34.99,
      status: "delivered",
      createdAt: "2024-06-18T13:30:00Z",
      paymentMethod: "Credit Card",
      deliveryFee: 5.99,
      paymentStatus: "paid",
   },
   {
      id: 7,
      userId: 5,
      totalAmount: 99.95,
      status: "delivered",
      createdAt: "2024-07-22T08:45:00Z",
      paymentMethod: "Credit Card",
      deliveryFee: 5.99,
      paymentStatus: "paid",
   },
   {
      id: 8,
      userId: 3,
      totalAmount: 19.99,
      status: "processing",
      createdAt: "2024-08-30T17:10:00Z",
      paymentMethod: "Credit Card",
      deliveryFee: 5.99,
      paymentStatus: "paid",
   },
   {
      id: 9,
      userId: 1,
      totalAmount: 64.97,
      status: "delivered",
      createdAt: "2024-09-14T12:25:00Z",
      paymentMethod: "Credit Card",
      deliveryFee: 5.99,
      paymentStatus: "paid",
   },
   {
      id: 10,
      userId: 4,
      totalAmount: 29.99,
      status: "pending",
      createdAt: "2024-10-01T15:50:00Z",
      paymentMethod: "Credit Card",
      deliveryFee: 5.99,
      paymentStatus: "paid",
   },
];
