import {
   type MovieCategory,
   type ProductItem,
   type ProductsByCategory,
} from "./datatType";

export const MoviesList: MovieCategory[] = [
   {
      id: "1",
      name: "My Neighbor Totoro",
      img: "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781421561226/my-neighbor-totoro-picture-book-new-edition-9781421561226_hr.jpg",
   },
   {
      id: "2",
      name: "Spirited Away",
      img: "https://example.com/spirited_away.jpg",
   },
   {
      id: "3",
      name: "Princess Mononoke",
      img: "https://example.com/princess_mononoke.jpg",
   },
   {
      id: "4",
      name: "Howl's Moving Castle",
      img: "https://example.com/howls_moving_castle.jpg",
   },
   {
      id: "5",
      name: "Kiki's Delivery Service",
      img: "https://s3.amazonaws.com/nightjarprod/content/uploads/sites/344/2026/03/13163130/Aufa4YdZIv4AXpR9rznwVA5SEfd-1-scaled.jpg",
   },
   { id: "6", name: "Ponyo", img: "https://example.com/ponyo.jpg" },
   {
      id: "7",
      name: "The Wind Rises",
      img: "https://example.com/the_wind_rises.jpg",
   },
   {
      id: "8",
      name: "Castle in the Sky",
      img: "https://example.com/castle_in_the_sky.jpg",
   },
   {
      id: "9",
      name: "Ponyo",
      img: "https://images.fathomevents.com/image/upload/w_400,dpr_2,f_auto,q_auto/v1743550042/Events/2025/2013/1000x1480_Ponyo_FE_Ticketing.jpg.jpg",
   },
   {
      id: "10",
      name: "Nausicaä of the Valley of the Wind",
      img: "https://example.com/nausicaa.jpg",
   },
];

export const mockProducts: ProductItem[] = [
   {
      id: 1,
      title: "Totoro Plush Toy",
      price: 29.99,
      description: "A soft and cuddly Totoro plush toy.",
      image: "https://enez76gwp29.exactdn.com/wp-content/uploads/2020/04/productimage208903327_2nd.jpg?strip=all&lossy=1&ssl=1",
      discount: 10,
      movieId: "1",
      stock: 0,
   },
   {
      id: 2,
      title: "Spirited Away Art Book",
      price: 19.99,
      description: "A beautiful art book featuring scenes from Spirited Away.",
      image: "https://enez76gwp29.exactdn.com/wp-content/uploads/2020/04/productimage120813380_2nd.jpg?strip=all&lossy=1&ssl=1",
      movieId: "2",
      stock: 0,
   },
   {
      id: 3,
      title: "My Neighbor Totoro T-Shirt",
      price: 24.99,
      description: "A stylish T-shirt with a Totoro design.",
      image: "https://i.ebayimg.com/images/g/GNcAAOSw7MNiYT6T/s-l1200.jpg",
      discount: 15,
      movieId: "1",
      stock: 0,
   },
   {
      id: 4,
      title: "Princess Mononoke Poster",
      price: 14.99,
      description: "A high-quality poster of Princess Mononoke.",
      image: "https://example.com/princess_mononoke.jpg",
      movieId: "3",
      stock: 0,
   },
   {
      id: 5,
      title: "Howl's Moving Castle Figurine",
      price: 39.99,
      description: "A detailed figurine of Howl's Moving Castle.",
      image: "https://example.com/howls_moving_castle.jpg",
      discount: 20,
      movieId: "4",
      stock: 0,
   },
   {
      id: 6,
      title: "Kiki's Delivery Service Tote Bag",
      price: 19.99,
      description: "A cute tote bag featuring Kiki's Delivery Service.",
      image: "https://example.com/kikis_delivery_service.jpg",
      movieId: "5",
      stock: 0,
   },
   {
      id: 7,
      title: "Ponyo Plush Toy",
      price: 29.99,
      description: "A soft and cuddly Ponyo plush toy.",
      image: "https://example.com/ponyo.jpg",
      movieId: "6",
      stock: 0,
   },
   {
      id: 8,
      title: "The Wind Rises Art Print",
      price: 24.99,
      description: "A beautiful art print of The Wind Rises.",
      image: "https://example.com/the_wind_rises.jpg",
      movieId: "7",
      stock: 0,
   },
   {
      id: 9,
      title: "Castle in the Sky Model Kit",
      price: 49.99,
      description: "A model kit of the iconic Castle in the Sky.",
      image: "https://example.com/castle_in_the_sky.jpg",
      movieId: "8",
      stock: 0,
   },
   {
      id: 10,
      title: "Grave of the Fireflies Soundtrack",
      price: 14.99,
      description: "The original soundtrack of Grave of the Fireflies.",
      image: "https://example.com/grave_of_the_fireflies.jpg",
      discount: 5,
      movieId: "9",
      stock: 0,
   },
   {
      id: 11,
      title: "Nausicaä of the Valley of the Wind Art Book",
      price: 19.99,
      description:
         "An art book featuring scenes from Nausicaä of the Valley of the Wind.",
      image: "https://example.com/nausicaa.jpg",
      movieId: "10",
      stock: 0,
   },
];

export const mockProductsByMovie: ProductsByCategory[] = [
   {
      movie: MoviesList[0],
      products: [
         {
            id: 1,
            title: "Totoro Plush Toy",
            price: 29.99,
            description: "A soft and cuddly Totoro plush toy.",
            image: "https://enez76gwp29.exactdn.com/wp-content/uploads/2020/04/productimage208903327_2nd.jpg?strip=all&lossy=1&ssl=1",
            discount: 10,
            movieId: "1",
            stock: 0,
         },
         {
            id: 2,
            title: "My Neighbor Totoro T-Shirt",
            price: 24.99,
            description: "A stylish T-shirt with a Totoro design.",
            image: "https://www.japan-experience.com/sites/default/files/styles/scale_crop_480x250/public/legacy/japan_experience/1497286956997.jpg.webp?h=ddb1ad0c&itok=BAVNd_Zu",
            discount: 15,
            movieId: "1",
            stock: 0,
         },
         {
            id: 11,
            title: "Totoro Keychain",
            price: 9.99,
            description: "A cute Totoro keychain to carry with you.",
            image: "https://images2.minutemediacdn.com/image/upload/c_fill,w_1200,ar_1:1,f_auto,q_auto,g_auto/shape/cover/sport/539787-c-1988-studio-ghibli-1-99691298d234359b7ea9eccc5925b9f3.jpg",
            movieId: "1",
            stock: 0,
         },
         {
            id: 12,
            title: "Totoro Mug",
            price: 14.99,
            description: "A ceramic mug featuring Totoro.",
            image: "https://i.redd.it/ovfk3xy2o4q51.jpg",
            discount: 5,
            movieId: "1",
            stock: 0,
         },
         {
            id: 13,
            title: "Totoro Wall Art",
            price: 19.99,
            description: "A beautiful wall art piece featuring Totoro.",
            image: "https://m.media-amazon.com/images/I/91400JsaK4L._AC_UF1000,1000_QL80_.jpg",
            movieId: "1",
            stock: 0,
         },
         {
            id: 14,
            title: "Totoro Backpack",
            price: 39.99,
            description: "A stylish backpack with a Totoro design.",
            image: "https://fictionmachine.com/wp-content/uploads/2015/04/totoro_head-e1601954323644.jpg?w=1024",
            discount: 20,
            movieId: "1",
            stock: 0,
         },
      ],
   },
   {
      movie: MoviesList[4],
      products: [
         {
            id: 3,
            title: "Kiki's Delivery Service Tote Bag",
            price: 19.99,
            description: "A cute tote bag featuring Kiki's Delivery Service.",
            image: "https://beam-images.warnermediacdn.com/BEAM_LWM_DELIVERABLES/b7788922-e4c4-42f8-918b-304a7a187f38/14865e51bde602ccf212e279d42a30974ccb791e.jpg?host=wbd-images.prod-vod.h264.io&partner=beamcom&w=500",
            movieId: "5",
            stock: 0,
         },
         {
            id: 4,
            title: "Kiki's Delivery Service Poster",
            price: 14.99,
            description: "A high-quality poster of Kiki's Delivery Service.",
            image: "https://static0.cbrimages.com/wordpress/wp-content/uploads/2019/08/kiki.jpg",
            movieId: "5",
            stock: 0,
         },
         {
            id: 15,
            title: "Kiki's Delivery Service Figurine",
            price: 29.99,
            description: "A detailed figurine of Kiki and Jiji.",
            image: "https://static.wikia.nocookie.net/studio-ghibli/images/b/b4/Jiji.jpg/revision/latest?cb=20210218143145",
            discount: 10,
            movieId: "5",
            stock: 0,
         },
         {
            id: 16,
            title: "Kiki's Delivery Service Hoodie",
            price: 49.99,
            description: "A cozy hoodie with a Kiki's Delivery Service design.",
            image: "https://i.guim.co.uk/img/media/70c3d88f9b85c23dca04051db41edf6c101de4a9/102_0_2000_1200/master/2000.jpg?width=700&quality=85&auto=format&fit=max&s=457387fd4068cc2812361031751a2b10",
            discount: 15,
            movieId: "5",
            stock: 0,
         },
      ],
   },
   {
      movie: MoviesList[8],
      products: [
         {
            id: 5,
            title: "Ponyo Plush Toy",
            price: 14.99,
            description: "A soft and cuddly Ponyo plush toy.",
            image: "https://d23.com/app/uploads/2015/07/ponyo-1180x600.jpg",
            movieId: "9",
            stock: 0,
         },
         {
            id: 26,
            title: "Ponyo T-Shirt",
            price: 19.99,
            description: "A stylish T-shirt with a Ponyo design.",
            image: "https://images.fathomevents.com/image/upload/w_2000,dpr_2,f_auto,q_auto/v1743550040/Events/2025/2013/1920x1080_Ponyo_Hero%20Image.jpg.jpg",
            discount: 10,
            movieId: "9",
            stock: 0,
         },
         {
            id: 27,
            title: "Ponyo Mug",
            price: 14.99,
            description: "A ceramic mug featuring Ponyo.",
            image: "https://corndogchats.com/wp-content/uploads/2016/04/ponyo-color-9.jpg?w=1200",
            movieId: "9",
            stock: 0,
         },
         {
            id: 28,
            title: "Ponyo Wall Art",
            price: 19.99,
            description: "A beautiful wall art piece featuring Ponyo.",
            image: "https://images.amcnetworks.com/ifccenter.com/wp-content/uploads/2019/12/ponyo_photo_02.jpg",
            discount: 5,
            movieId: "9",
            stock: 0,
         },
      ],
   },
];
